"""Opening snapshot diff: every unit of every chapter battle at the original's round-1 halt against
the remake's same moment, every live-record field side by side — registry task `opening_snapshot`.

Inputs (untracked, regenerated by the two exporters; `hsl generate opening_snapshot` reads them):

  ignored/opening_snapshot/original/L051_g0.json, L051_g1_s1.json ...
      tools/hsltools/probes/_opening_snapshot.py — the original entered to its first round-queue
      sort 0x407340, every registry object's whole live record (0x1fc bytes)
  ignored/opening_snapshot/remake/L051.json
      tests/diagnostics/export_opening_snapshot.gd — the remake PlayLoop after create → births →
      begin_battle, every unit dictionary plus derived extras

Modes: g0 = growth false on both sides (the original zeroes the growth words +0x1f8／+0x1fa at
0x43eefb／0x44345d, the remake gives every non-player birth adjust_level [0, 0]): every field is
deterministic except the pmEnemy carry roll 0x407c40 (bag) and the object frame delay 0x407dba.
g1 = the real opening births under global seeds (the original's words [t, t ^ 0xe54a231c] written
before 0x42da60; the remake GlobalRandomStream.seeded(t)). The remake does not draw the frame delay
rand(24), so the two streams part at the first birth: a g1 field listed in RANDOM_G1 passes when
each original value lies inside the remake's support — its range over its seeds widened by each
birth's lowest／highest outcome (the exporter's `bounds`: every 0x40e870 draw at 0 or bound − 1;
level, gains, stamina, gold and kill EXP all rise with the draws). A constant remake field is an
exact comparison; every other field is compared exactly.

Pairing: registry slot order (SLOTORDER: 139 battlefields agree) — reserved player slots 0..19 by
slot, NPC slots from 20 aligned by PLAYERS code (difflib) so a unit only one side has at the halt
does not shift the rest; an aligned pair of different codes is a `code` row. Units of one code whose
cells disagree are re-paired by exact cell when the other side has it (a `registry_slot` row: the
same units registered in another order); a cell difference left over is labelled by its placement
source (cell_cause: cell:random／cell:blocked／cell:offgrid／cell).

Field table FIELDS: the named live-record offsets (original_save_format.md, hsltools.data.
original_save_members.REC, original_status_effects.md, original_ai_navigation.md instance words,
original_weapon_effects.md) with the remake value each maps to; named fields without a remake
value are listed unmapped, every other 4-byte word of the record is `unknown_0xNNN` (reported,
not compared). FIELD_NOTES carries, for each field with a difference, the original reading
(address) and the attribution (data generator, rule, mapping or harness); a new difference
without a note fails generate.

check validates the tracked report offline (totals and leaderboard recount from the rows, the
three fixed fields max_hp／stamina／items at zero as the differ's self-check, md = render(json));
generate rebuilds it from the ignored snapshots (NotGeneratable when they are absent).

PASS: OPENING_SNAPSHOT_CHECK_PASS battles=N compared=N units=N fields=N diff_rows=N diff_units=N
unknown_offsets=N self_check=max_hp:0,stamina:0,items:0
"""
from __future__ import annotations

import dataclasses
import difflib
import json
import re
import struct
from collections import Counter, defaultdict
from pathlib import Path
from typing import Callable

from hsltools.paths import ROOT
from hsltools.registry import CheckFailed, Context, NotGeneratable, Task

REPORT_JSON = 'content/generated/hsl/development/opening_snapshot_diff.json'
REPORT_MD = 'content/generated/hsl/development/opening_snapshot_diff.md'
RAW = ROOT / 'ignored/opening_snapshot'
LEVELS_SOURCE = ROOT / 'content/generated/hsl/development/autoplay/results.json'
TYPE_H = ROOT / 'content/imported/hsl/global/tables/TYPE.H'
SCHEMA = 'hsl_opening_snapshot_diff.v1'
RECORD_SIZE = 0x1fc
RESERVED_SLOTS = 20
SELF_CHECK = ('max_hp', 'stamina', 'items')   # fixed by HANKS3／DATA9, STAMINA-RULE, ALLYHEAL
NO_ORIGINAL = {200: 'remake-authored level, the original has no level 200'}


def _path(*keys: str) -> Callable[[dict], object]:
    def get(unit: dict):
        value = unit
        for key in keys:
            if not isinstance(value, dict) or key not in value:
                return None
            value = value[key]
        return value
    return get


def _equipment(slot: str) -> Callable[[dict], int]:
    def get(unit: dict) -> int:
        return next((int(e['item_code']) for e in unit.get('equipment', []) if e.get('slot') == slot), 0)
    return get


def _dead_message(unit: dict):
    """The death-line ids the remake speaks from (own `dead_message`, else the PLAYERS pair of
    aftermath.json); compared with the nonzero halves of +0x14 as a set — the remake list does not
    keep which half an id sat in (obj_Data8 374 is the low half, a PLAYERS pair is hi／lo)."""
    ids = unit['extra'].get('dead_message_ids')
    return None if ids is None else sorted(int(i) for i in ids)


def _mode(unit: dict):
    """player_mode; a curated scenario without one has only the role's side (compared as +0x28 & 0x70000)."""
    return unit['player_mode'] if 'player_mode' in unit else {'side': unit['extra']['side_mask']}


# +0xa0 bits (original_field_coverage.md PLAYERS flags): 0x1 move_fly, 0x2 no_attack, 0x4 undead
# (actSetPlayerUndead, opcode 64 → 0x4521fb: |= 4 or &= ~4), 0x8 side swap (0x407ec0 obj_Data9, 0x450710), 0x10 no_block, 0x40 no_poison, 0x200 double_attack, 0x400
# move_magic_use, 0x800 no_paralyze, 0x1000 no_disablemagic, 0x2000 no_weaken, 0x4000 st_x2; the
# presentation bits 0x20 no_showshape／0x100 no_shadow are not compared (unconsumed, field_coverage).
CAPABILITY_PRESENTATION = 0x120


def _capability(unit: dict) -> int:
    extra, traversal = unit['extra'], unit.get('traversal', {})
    return (int(extra.get('status_capability_flags', 0)) | (2 if unit.get('no_attack') else 0)
            | (1 if traversal.get('flying') else 0) | (0x10 if traversal.get('no_block') else 0)
            | (0x200 if extra.get('double_attack') else 0) | (0x400 if extra.get('move_magic_use') else 0)
            | (4 if unit.get('undead') else 0) | (8 if unit.get('side_swapped') else 0))


def _half(getter: Callable[[dict], object], default_zero: bool = False) -> Callable[[dict], object]:
    def get(unit: dict):
        value = getter(unit)
        return 0 if value is None and default_zero else value
    return get


@dataclasses.dataclass(frozen=True)
class Field:
    name: str
    offset: int
    fmt: str                        # u32 i32 u16 i16, or items／special／magic (decoded lists)
    remake: Callable[[dict], object] | None
    reading: str
    size: int = 0

    @property
    def width(self) -> int:
        return self.size or {'u32': 4, 'i32': 4, 'u16': 2, 'i16': 2}[self.fmt]


def _field(name, offset, fmt, remake, reading, size=0) -> Field:
    return Field(name, offset, fmt, remake, reading, size)


P = _path
FIELDS: tuple[Field, ...] = (
    _field('code', 0x00, 'u32', lambda u: int(u['actor_id']), 'PLAYERS code (0x44cb10 template copy)'),
    _field('name_id', 0x04, 'u32', None, 'name resource id'),
    _field('sound_walk_dead', 0x08, 'u32', None, 'WAV handles walk／dead'),
    _field('sound_miss_attack', 0x0c, 'u32', None, 'WAV handles miss／attack'),
    _field('sound_hit_walkwater', 0x10, 'u32', None, 'WAV handles hit／walkwater'),
    _field('dead_message', 0x14, 'u32', _dead_message, 'dead-message ids hi／lo (0x407ec0 obj_Data8, actSetDeadMessage)'),
    _field('job', 0x18, 'u32', P('growth_profile', 'job_code'), 'job row (0x448840 reads it)'),
    _field('job_show_name', 0x1c, 'u32', None, 'title text id'),
    _field('class', 0x20, 'u16', None, 'TYPE.H class (classHuman 101 ...)'),
    _field('sound_shoothit', 0x22, 'u16', None, 'WAV handle shoothit'),
    _field('status_flags', 0x24, 'u32', P('status_flags'), 'status bits 1 poison 2 no-magic 4 paralysis 8 weaken 0x10／0x20／0x40 ups'),
    _field('mode', 0x28, 'u32', _mode, 'player mode word (0x407ec0 obj_Data9 swap, 0x450710)'),
    _field('size', 0x2c, 'u16', P('traversal', 'size_type'), 'large-body word (0x409090, 0x4448f4)'),
    _field('carry_row', 0x2e, 'u16', None, 'PLAYERS carry_item row index (0x407c40 → 0x44e100)'),
    _field('poison', 0x30, 'u32', _half(P('status_counters', 'poison'), True), 'poison duration lo／strength hi (0x4091b0, 0x40b910)'),
    _field('no_magic', 0x34, 'u32', _half(P('status_counters', 'no_magic'), True), 'no-magic duration (0x409210)'),
    _field('weaken', 0x38, 'u32', _half(P('status_counters', 'weaken'), True), 'weaken duration lo／power hi (0x409240)'),
    _field('paralysis', 0x3c, 'u32', _half(P('status_counters', 'paralysis'), True), 'paralysis duration (0x409110)'),
    _field('attack_up', 0x40, 'u32', _half(P('status_counters', 'attack_up'), True), 'attack-up word (flag 0x10)'),
    _field('defense_up', 0x44, 'u32', _half(P('status_counters', 'defense_up'), True), 'defense-up word (flag 0x20)'),
    _field('resist_up', 0x48, 'u32', _half(P('status_counters', 'resist_up'), True), 'resist-up word (flag 0x40, 0x448903)'),
    _field('str', 0x4c, 'i32', P('combat_profile', 'str'), 'working str'),
    _field('dex', 0x50, 'i32', P('combat_profile', 'dex'), 'working dex'),
    _field('mind', 0x54, 'i32', P('combat_profile', 'mind'), 'working mind'),
    _field('con', 0x58, 'i32', P('combat_profile', 'con'), 'working con'),
    _field('face', 0x5c, 'u32', None, 'portrait shape handle'),
    _field('job_up_code', 0x60, 'u32', None, 'job-up object code (0x4348f0 admits by it)'),
    _field('base_str', 0x64, 'i32', P('combat_profile', 'str'), 'base str (the remake keeps one attribute row)'),
    _field('base_dex', 0x68, 'i32', P('combat_profile', 'dex'), 'base dex'),
    _field('base_mind', 0x6c, 'i32', P('combat_profile', 'mind'), 'base mind'),
    _field('base_con', 0x70, 'i32', P('combat_profile', 'con'), 'base con'),
    _field('cap_str', 0x74, 'i32', P('growth_profile', 'caps', 'str'), 'str cap (0x448840 from the job row)'),
    _field('cap_dex', 0x78, 'i32', P('growth_profile', 'caps', 'dex'), 'dex cap'),
    _field('cap_mind', 0x7c, 'i32', P('growth_profile', 'caps', 'mind'), 'mind cap'),
    _field('cap_con', 0x80, 'i32', P('growth_profile', 'caps', 'con'), 'con cap'),
    _field('install_code', 0x84, 'u32', None, 'install-time code word (0x407ec0; STORY objects: 0x451155)'),
    _field('exp', 0x88, 'i32', P('exp'), 'experience'),
    _field('exp_threshold', 0x8c, 'i32', P('extra', 'exp_threshold'), 'next-level threshold (0x448840 → 0x44b678)'),
    _field('kill_exp', 0x90, 'i32', P('kill_exp'), 'EXP a killer gains (0x40e390)'),
    _field('gold', 0x98, 'i32', P('extra', 'carried_gold'), 'kill gold／carried gold (EVEF word 0 at 0x42bd50, 0x40e870 raise)'),
    _field('level', 0x9c, 'i32', P('level'), 'level'),
    _field('capability', 0xa0, 'u32', _capability, 'capability bits (PLAYERS status words, 0x200 double attack, 8 side swap 0x446be0)'),
    _field('kill_chain', 0xa8, 'u32', _half(P('kill_chain_word'), True), 'kill chain word (0x442720)'),
    _field('hit_bonus', 0xb0, 'i32', _half(P('hit_bonus_accum'), True), 'hit compensation (0x44240d)'),
    _field('defense', 0xb4, 'i32', P('combat_profile', 'live_defense'), 'defense (0x448840)'),
    _field('speed', 0xb8, 'i32', P('live_speed'), 'speed, the queue key 0x407340 sorts on'),
    _field('hit_ratio', 0xbc, 'i32', P('combat_profile', 'live_hit_ratio'), 'hit ratio'),
    _field('attack', 0xc0, 'i32', P('combat_profile', 'live_attack_damage'), 'attack'),
    _field('weapon_magic_type', 0xc4, 'i32', P('combat_profile', 'weapon_magic_attack_type'), 'weapon element (0x409be0)'),
    _field('weapon_low', 0xc8, 'i32', P('combat_profile', 'weapon_damage_variance_lo'), 'weapon damage low'),
    _field('weapon_high', 0xcc, 'i32', P('combat_profile', 'weapon_damage_variance_hi'), 'weapon damage high'),
    _field('magic_attack', 0xd0, 'i32', P('combat_profile', 'live_magic_attack'), 'magic attack'),
    _field('magic_hit', 0xd4, 'i32', None, 'equipment magic hit (0x4485b6)'),
    _field('hp', 0xd8, 'i32', P('hp'), 'HP'),
    _field('max_hp', 0xdc, 'i32', P('max_hp'), 'max HP (0x448840, hp_level by +0x28 at the refresh)'),
    _field('mp', 0xe0, 'i32', P('mp'), 'MP'),
    _field('max_mp', 0xe4, 'i32', P('max_mp'), 'max MP'),
    _field('stamina', 0xe8, 'i32', P('stamina'), 'stamina (0x44cb41 template copy, 0x407632 carry clear, 0x40e870 rand(11))'),
    _field('weapon', 0xec, 'i32', _equipment('weapon'), 'equipment weapon'),
    _field('head', 0xf0, 'i32', _equipment('head'), 'equipment head'),
    _field('armor', 0xf4, 'i32', _equipment('armor'), 'equipment armor'),
    _field('foot', 0xf8, 'i32', _equipment('foot'), 'equipment foot'),
    _field('other1', 0xfc, 'i32', _equipment('accessory1'), 'equipment accessory 1'),
    _field('other2', 0x100, 'i32', _equipment('accessory2'), 'equipment accessory 2'),
    *(_field(f'resist_work.{i}', 0x104 + 4 * i, 'i32', P('combat_profile', 'resist_by_type', str(i)), f'working resist {i}') for i in range(5)),
    *(_field(f'resist_base.{i}', 0x118 + 4 * i, 'i32', P('extra', 'source', 'base_resist_by_type', str(i)), f'base resist {i}') for i in range(5)),
    _field('move_work', 0x12c, 'i32', P('move_point'), 'move points (0x448840)'),
    _field('move', 0x130, 'i32', P('base_move_point'), 'base move'),
    _field('job_up_flags', 0x134, 'u32', _half(P('job_up_flags'), True), 'job-up tier bits (0x4348f0)'),
    _field('items', 0x138, 'items', P('inventory'), 'bag, 8 slots (0x44cb10 template copy + 0x407c40 carry into the first empty slot)', 32),
    _field('special_skills', 0x158, 'special', P('extra', 'skill_ids'), 'special words by element, bit code-1', 28),
    _field('magic_skills', 0x174, 'magic', P('extra', 'skill_ids'), 'magic words by element, bit code-1', 24),
    _field('effect_flags', 0x18c, 'u32', None, 'equipment／capability effect bits (0x448840 → 0x448420)'),
    _field('steal_base', 0x194, 'u16', P('combat_profile', 'base_steal_ratio'), 'steal word (PLAYERS steal_ratio)'),
    _field('steal_work', 0x196, 'u16', P('combat_profile', 'steal_ratio'), 'steal work (word or 12, + item)'),
    _field('avoid_base', 0x198, 'u16', P('extra', 'source', 'avoid_hit_ratio'), 'avoid word'),
    _field('avoid_work', 0x19a, 'u16', P('combat_profile', 'avoid_hit_ratio'), 'avoid work'),
    _field('attack_back_base', 0x19c, 'u16', P('extra', 'source', 'attack_back'), 'counter word'),
    _field('attack_back_work', 0x19e, 'u16', P('combat_profile', 'attack_back'), 'counter work (word or 12, + item)'),
    _field('damagex2_base', 0x1a0, 'u16', P('extra', 'source', 'attack_damagex2'), 'critical word'),
    _field('damagex2_work', 0x1a2, 'u16', P('combat_profile', 'attack_damagex2'), 'critical work (word or 8, + item)'),
    _field('add_attack', 0x1a4, 'i32', P('extra', 'source', 'attack_power'), 'source attack word (+ 0x40e870 gain)'),
    _field('add_magic', 0x1a8, 'i32', P('extra', 'source', 'magic_attack_power'), 'source magic attack word (+ gain)'),
    _field('add_defense', 0x1ac, 'i32', P('extra', 'source', 'defense'), 'source defense word'),
    _field('add_speed', 0x1b0, 'i32', P('extra', 'source', 'speed'), 'source speed word (+ gain)'),
    _field('add_mp', 0x1b4, 'i16', P('extra', 'source', 'magic_point'), 'source MP word (+ gain)'),
    _field('add_hp', 0x1b6, 'i16', P('extra', 'source', 'hit_point'), 'source HP word (+ gain)'),
    _field('wait_round', 0x1b8, 'i32', P('ai_wait_remaining'), 'wait_round countdown (loader 0x44c7e0, opcode 33)'),
    _field('find_no_id', 0x1bc, 'i32', P('extra', 'ai_profile', 'find_no_id'), 'AI find_no_id (PLAYERS SID code the scan skips, −1 none)'),
    *(_field(key, offset, 'i32', P('extra', 'ai_profile', key), f'AI instance word {key} (loader 0x44c7e0, EVEF words)')
      for key, offset in (('find_type', 0x1c0), ('find_flag', 0x1c4), ('find_range', 0x1c8), ('ai_call_range', 0x1cc),
                          ('ai_fixed', 0x1d0), ('ai_check_dying', 0x1d4), ('ai_check_hp', 0x1d8), ('ai_help_otherhp', 0x1dc),
                          ('ai_help_status', 0x1e0), ('ai_help_attack', 0x1e4), ('ai_lock', 0x1e8), ('ai_att_special', 0x1ec),
                          ('ai_att_magic', 0x1f0), ('ai_magic_multi_first', 0x1f4))),
    _field('growth_disp', 0x1f8, 'u16', lambda u: _growth_parameter(u, 1), 'level-adjust dispersion (0x44ca64, opcode 56, EVEF word 17)'),
    _field('growth_range', 0x1fa, 'u16', lambda u: _growth_parameter(u, 0), 'level-adjust range (0x44ca64, opcode 56, EVEF word 16)'),
)
# Object words beside the record: compared as fields of their own.
OBJECT_FIELDS = ('cell', 'held_target')
# Zeroed by the g0 harness on the original side (growth false), not a comparison there.
G0_SKIP = {'growth_disp', 'growth_range'}
# The fields the g1 opening births draw (0x40e870: level, attributes, EXP, stamina rand(11), gold,
# kill EXP, source gains; 0x407c40 carry) and everything the 0x448840 refresh derives from them.
RANDOM_G1 = {'level', 'exp', 'exp_threshold', 'kill_exp', 'gold', 'stamina', 'str', 'dex', 'mind', 'con',
             'base_str', 'base_dex', 'base_mind', 'base_con', 'hp', 'max_hp', 'mp', 'max_mp', 'defense', 'speed',
             'hit_ratio', 'attack', 'magic_attack', *(f'resist_work.{i}' for i in range(5)), 'add_attack', 'add_magic',
             'add_speed', 'add_mp', 'add_hp', 'items'}


def _growth_parameter(unit: dict, index: int):
    pair = unit['extra'].get('growth_parameters')
    return None if pair is None else int(pair[index])


# Per differing field: the original reading, the remake's current state, and the attribution
# (data = data generator, rule = rule, mapping = export mapping, harness = the two exporters'
# setups). Filled from the measured rows; generate fails on a differing field without a note.
FIELD_NOTES: dict[str, dict[str, str]] = {
    'weapon_magic_type': {
        'reading': '无武器单位（061／062／064／067 村民、100 门、101 船壳等）live +0xc4 = 0：模板表该字为 0，0x448840 只在有武器时经 0x448420 写元素；有武器无元素的写 −1',
        'remake': 'EquipmentRules.effect_delta 无武器时写 −1；无武器单位原版 AI 不出手（0x409090 返回 0）也无反击射程，预计无可见后果',
        'attribution': 'data：无武器默认值'},
    'cell:offgrid': {
        'reading': '不在 32 px 网格上的 STORY 终点，原版格子＝像素 >> 5（向下取整）',
        'remake': 'battle.py 按像素 >> 5 向下取整',
        'attribution': 'data：生成器量化方式'},
    'cell:random': {
        'reading': '37 关 actInsertObjectRandomPos 插入的 066／067：原版 actSetRandomPos 0x451d0f 对 5 个槽逐个抽全局流 0x458c10（0x4795d4／0x4795d8），奇数就与槽 (i+2) mod 5 对换；原版在开局第 911–935 次抽取处洗牌（之前 877 次是开场走位的平局硬币 0x413862），4 次运行排列 g0／s3 为 3,4,1,2,5、s1 为 3,5,1,2,4、s2 为 2,3,5,1,4（快照按格给单位起名，排列只在登记槽序里）；38 关 034_2 随机落点后 actWalkDisp 终点 [14,11] 是 0xff 格，原版停在前一格 [13,11]',
        'remake': 'BattleLoopInit._load_opening_story_state 用同一洗牌算法，但在建循环、出生之前抽（新种子流的头几位），抽取时机与原版不同，逐值对不上',
        'attribution': 'random：抽取时机（前置 900 余次抽取不复现），只求分布'},
    'mode': {
        'reading': '1 关村民 061／062 live +0x28 = 0x50000（pmNPCPlayer）',
        'remake': 'ohm_village.py 写 PLAYERS mode（OPENFIX 前无 player_mode，按 friendly_ai 角色推成 0x10000）',
        'attribution': 'data：手写场景缺阵营字'},
    'items:evef': {
        'reading': '原版 0x44cb10 复制模板背包后，0x42be2e..0x42be79 把 EVEF 实例物品字逐个追加到第一个空槽（52 关 024 [241,241]、33／41 关 056 [252,10]／[252,170]、40 关 055 [252,142]、75 关 054 [252,137]）',
        'remake': 'ActorInitializationRules.apply_instance_words 用 inventory.find(0) 找空槽，模板背包来自 JSON（浮点 0.0），find(0) 恒为 −1，实例物品全被丢；4840921c 起影响 055／056，ALLYHEAL c09cfedb 给 024／054 加模板背包后扩到 52／75 关',
        'attribution': 'rule：代码类型错（int 与 float 比较）'},
    'dead_message': {
        'reading': '1／2 关雷歐納德、琥的 +0x14 高半字是 RESOURCE 741–743 的死亡台词（开场脚本 actSetDeadMessage 写入）',
        'remake': 'ohm_village.py／gol_road.py 应用 STORY actSetDeadMessage（OPENFIX 前没带这两句）',
        'attribution': 'data：手写场景缺脚本写入'},
    'capability': {
        'reading': '79 关 057 live +0xa0 带 0x4000（PLAYERS st_x2，气力双倍；0x448840 映射到 +0x18c 0x40）',
        'remake': '单位不带 PLAYERS st_x2（StaminaRules.effects 只读装备），019／057 气力不加倍',
        'attribution': 'data：PLAYERS 能力位未进单位'},
    'cell': {
        'reading': '3 名 STORY 走位终点落在 0xff 格的单位原版没停在终点：80 关嚎 actWalk 终点 [5,22] 原版站 [5,19]（沿路最后一个可站格），34 关 037_2／037_3 actWalkDisp 终点 [36,17]／[38,20] 原版站 [34,17]／[37,20]（越过终点的第一个可站格）；另 53 名单格单位原版停在 0xff 终点，区分条件未追',
        'remake': 'battle.py 让单格单位停在阻挡终点（cell:blocked 那 53 名的原版读法）',
        'attribution': 'data：待查（原版 STORY 走位遇 0xff 的停点规则）'},
    'job_up_flags': {
        'reading': '80 关 068（obj_Story_Level_Enemy68Star）obj_Y1 = 90，0x407ec0／0x42bf3b 写 live +0x134 低半字',
        'remake': 'obj_Y1 未进数据链（字段覆盖表已列 unconsumed），+0x134 这半字的读者未追',
        'attribution': 'data：字段未消费'},
}


def magic_groups() -> dict[int, str]:
    text = TYPE_H.read_bytes().decode('cp950', 'replace')
    return {int(v): n for n, v in re.findall(r'#define\s+(magic[A-Z][A-Z0-9]*)\s+(\d+)', text) if int(v) <= 6}


def covered_words() -> set[int]:
    words = set()
    for field in FIELDS:
        for at in range(field.offset & ~3, field.offset + field.width, 4):
            words.add(at)
    return words


UNKNOWN_OFFSETS = tuple(at for at in range(0, RECORD_SIZE, 4) if at not in covered_words())


def decode(record: bytes, groups: dict[int, str]) -> dict[str, object]:
    out: dict[str, object] = {}
    for field in FIELDS:
        if field.fmt in ('u32', 'i32', 'u16', 'i16'):
            code = {'u32': '<I', 'i32': '<i', 'u16': '<H', 'i16': '<h'}[field.fmt]
            out[field.name] = struct.unpack_from(code, record, field.offset)[0]
        elif field.fmt == 'items':
            out[field.name] = list(struct.unpack_from('<8i', record, field.offset))
        else:
            count = field.width // 4
            words = struct.unpack_from(f'<{count}I', record, field.offset)
            out[field.name] = sorted(f'{field.fmt}:{groups.get(g, f"group{g}")}:magicCode{bit + 1:02d}'
                                     for g, word in enumerate(words) for bit in range(32) if word >> bit & 1)
    for at in UNKNOWN_OFFSETS:
        out[f'unknown_{at:#05x}'] = struct.unpack_from('<I', record, at)[0]
    return out


def remake_fields(unit: dict) -> dict[str, object]:
    out: dict[str, object] = {}
    for field in FIELDS:
        if field.remake is None:
            continue
        value = field.remake(unit)
        if field.fmt in ('special', 'magic'):
            value = sorted(s for s in (value or []) if s.startswith(field.fmt + ':'))
        elif field.fmt == 'items' or isinstance(value, (list, dict)):
            value = [int(v) for v in value] if isinstance(value, list) else value
        elif value is not None:
            value = int(value)
        out[field.name] = value
    out['cell'] = list(unit.get('coord', []))
    return out


def bound_units(unit: dict) -> list[dict]:
    """The unit as its birth's lowest and highest outcome (exporter `extra.bounds`)."""
    out = []
    for bound in unit['extra'].get('bounds', {}).values():
        synthetic = dict(unit, **{k: v for k, v in bound.items() if k not in ('source', 'exp_threshold', 'carried_gold')})
        synthetic['extra'] = dict(unit['extra'], **{k: bound[k] for k in ('source', 'exp_threshold', 'carried_gold') if k in bound})
        out.append(synthetic)
    return out


def same(name: str, mine, value) -> bool:
    """Exact comparison, with the two views that are not one word on the remake side."""
    if name == 'mode' and isinstance(value, dict):
        return mine & 0x70000 == value['side']
    if name == 'capability':
        return mine & ~CAPABILITY_PRESENTATION == value
    if name == 'dead_message':
        return sorted(h for h in (mine >> 16, mine & 0xffff) if h) == value
    return mine == value


def feasible_bags(unit: dict) -> list[list[int]]:
    """The bags the remake's births can leave: the pre-birth bag, and for an enemy_ai (the pmEnemy
    branch of 0x407cc0) that bag with one carry-list code in its first empty slot (0x436e30)."""
    base = [int(v) for v in unit['extra'].get('inventory_template', unit.get('inventory', []))]
    bags = [base]
    if unit.get('battle_actor_role') == 'enemy_ai':
        for code in unit['extra'].get('carry_items', []):
            if int(code) > 0 and 0 in base:
                bag = list(base)
                bag[bag.index(0)] = int(code)
                bags.append(bag)
    return bags


def evef_items(level: int) -> dict[str, list[int]]:
    """EVEF instance item words per remake unit id (the scenario's evef_instance.items; 0x42be2e appends
    them after the template bag)."""
    path = battle_path(level)
    units = json.loads(path.read_text(encoding='utf-8')).get('playable_units', []) if path.exists() else []
    return {u['id']: [int(c) for c in u.get('evef_instance', {}).get('items', [])] for u in units if u.get('evef_instance', {}).get('items')}


def battle_path(level: int) -> Path:
    entry = _load(ROOT / 'content/battles/campaign.json')['battles'].get(str(level), {})
    scenario = str(entry.get('scenario', ''))
    return ROOT / scenario.removeprefix('res://') if scenario else ROOT / f'content/battles/battle_{level:03d}.json'


TEMPLATE_BAGS = ROOT / 'content/imported/hsl/chapter01/consumables.json'


def with_instance_items(unit: dict, items: list[int]) -> dict:
    """The unit with the pre-birth bag the two original writes leave: the PLAYERS template bag
    (0x44cb10, consumables.json initial_inventory) and each EVEF instance item in the first empty slot
    (0x42be2e..0x42be79)."""
    bags = _load(TEMPLATE_BAGS)['initial_inventory']
    bag = [int(v) for v in bags.get(str(unit['actor_id']), [0] * 8)]
    for code in items:
        if 0 in bag:
            bag[bag.index(0)] = code
    return dict(unit, extra=dict(unit['extra'], inventory_template=bag))


def pair_units(original: list[dict], remake: list[dict]) -> tuple[list[tuple[dict, dict]], list[dict], list[dict]]:
    """(pairs, original only, remake only) in registry-slot order: reserved slots by slot, NPC slots
    aligned by PLAYERS code."""
    code_of = lambda unit: struct.unpack_from('<I', bytes.fromhex(unit['record']), 0)[0]
    by_slot = {u['extra']['registry_slot']: u for u in remake if u['extra']['registry_slot'] < RESERVED_SLOTS}
    pairs, only_original, only_remake = [], [], []
    for unit in (u for u in original if u['slot'] < RESERVED_SLOTS):
        match = by_slot.pop(unit['slot'], None)
        (pairs.append((unit, match)) if match is not None else only_original.append(unit))
    only_remake += list(by_slot.values())
    npcs_o = [u for u in original if u['slot'] >= RESERVED_SLOTS]
    npcs_r = sorted((u for u in remake if u['extra']['registry_slot'] >= RESERVED_SLOTS), key=lambda u: u['extra']['registry_slot'])
    matcher = difflib.SequenceMatcher(None, [code_of(u) for u in npcs_o], [int(u['actor_id']) for u in npcs_r], autojunk=False)
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == 'equal' or (tag == 'replace' and i2 - i1 == j2 - j1):
            pairs += list(zip(npcs_o[i1:i2], npcs_r[j1:j2]))
        else:
            only_original += npcs_o[i1:i2]
            only_remake += npcs_r[j1:j2]
    return pairs, only_original, only_remake


def resolve_swaps(pairs: list[tuple[dict, dict]]) -> tuple[list[tuple[dict, dict]], set[int]]:
    """Slot-order pairs of one PLAYERS code whose cells disagree, re-paired by exact cell where the
    other side has that cell: the same units registered in another order. Returns the pairs and the
    id() of each re-paired original (a `registry_slot` row)."""
    code_of = lambda unit: struct.unpack_from('<I', bytes.fromhex(unit['record']), 0)[0]
    loose: dict[int, list[int]] = defaultdict(list)
    for index, (o_unit, r_unit) in enumerate(pairs):
        if o_unit['cell'] != list(r_unit.get('coord', [])) and not random_placement(r_unit):
            loose[code_of(o_unit)].append(index)
    pairs = list(pairs)
    moved: set[int] = set()
    for indices in loose.values():
        free = {i: pairs[i][1] for i in indices}
        for i in indices:
            o_unit = pairs[i][0]
            j = next((j for j, r_unit in free.items() if list(r_unit.get('coord', [])) == o_unit['cell']), None)
            if j is not None and j != i:
                moved.add(id(o_unit))
            if j is not None:
                pairs[i] = (o_unit, free.pop(j))
        leftovers = [i for i in indices if list(pairs[i][1].get('coord', [])) != pairs[i][0]['cell']]
        for i, r_unit in zip(leftovers, free.values()):
            pairs[i] = (pairs[i][0], r_unit)
    return pairs, moved


RANDOM_PLACEMENTS = ('actInsertObjectRandomPos', 'actInsertStoryObjectRandomPos', 'actInsertRandomObject', 'actInsertStoryObjectWaitPos')


def random_placement(unit: dict) -> bool:
    return any(action in RANDOM_PLACEMENTS for action in unit['extra'].get('position', {}).get('actions', []))


def cell_cause(original_cell: list[int], unit: dict) -> str:
    """Which placement rule a cell difference comes from: `cell:random` (a random-position insert the
    remake pre-bakes to one point), `cell:blocked` (the assembler moved the unit off a cell its terrain
    reading calls blocked; the original stands on it), `cell:offgrid` (an off-grid STORY endpoint the
    original floors with pixel >> 5), `cell` otherwise."""
    placed = unit['extra'].get('position', {})
    if any(action in RANDOM_PLACEMENTS for action in placed.get('actions', [])):
        return 'cell:random'
    if placed.get('blocked_source_cell') == original_cell:
        return 'cell:blocked'
    end = placed.get('story_endpoint')
    if placed.get('unaligned') and end and [end[0] >> 5, end[1] >> 5] == original_cell:
        return 'cell:offgrid'
    return 'cell'


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding='utf-8'))


def build(root: Path = RAW, only: list[int] | None = None) -> dict:
    groups = magic_groups()
    levels = only or sorted(int(level) for level in _load(LEVELS_SOURCE)['levels'])
    rows: list[list] = []
    skipped, pairing_rows, compared_levels = [], [], []
    compared = Counter()
    not_exported = Counter()
    unknown_values: dict[str, Counter] = defaultdict(Counter)
    unmapped_values: dict[str, Counter] = defaultdict(Counter)
    units_paired = 0
    g1_seeds_original: set[int] = set()
    g1_seeds_remake: set[int] = set()
    unmapped = [f.name for f in FIELDS if f.remake is None]
    for level in levels:
        if level in NO_ORIGINAL:
            skipped.append({'level': level, 'reason': NO_ORIGINAL[level]})
            continue
        remake_path = root / 'remake' / f'L{level:03d}.json'
        originals = sorted((root / 'original').glob(f'L{level:03d}_g*.json'))
        if not remake_path.exists() or not originals:
            raise NotGeneratable(f'opening_snapshot: level {level} snapshots missing under {root} (run _opening_snapshot.py and '
                                 f'export_opening_snapshot.gd)')
        remake = _load(remake_path)['runs']
        errors = [(p.stem, _load(p).get('error')) for p in originals if _load(p).get('error')]
        errors += [(key, run['error']) for key, run in remake.items() if run.get('error')]
        if errors:
            skipped.append({'level': level, 'reason': '; '.join(f'{k}: {e}' for k, e in errors)})
            continue
        compared_levels.append(level)
        instance_items = evef_items(level)
        seen_cells: dict[str, set] = defaultdict(set)   # original cells per remake unit over the runs
        remake_cells: dict[str, list] = {}
        g1_remake = {key: run for key, run in remake.items() if key.startswith('g1_')}
        g1_seeds_remake |= {int(key[4:]) for key in g1_remake}
        # Remake range over its g1 seeds, per unit id and field (numbers) — the support a random field may take.
        spans: dict[str, dict[str, list]] = defaultdict(dict)
        for run in g1_remake.values():
            for unit in run['units']:
                for view in [unit] + bound_units(unit):
                    for name, value in remake_fields(view).items():
                        if name in RANDOM_G1 and isinstance(value, int):
                            low, high = spans[unit['id']].get(name, [value, value])
                            spans[unit['id']][name] = [min(low, value), max(high, value)]
        for path in originals:
            original = _load(path)
            mode, seed = original['mode'], original['seed']
            if mode == 'g1':
                g1_seeds_original.add(seed)
            run_key = f'{mode}_s{seed}' if mode == 'g1' else 'g0_s1'
            run = remake.get(run_key) or (next(iter(g1_remake.values())) if mode == 'g1' else None)
            if run is None:
                raise NotGeneratable(f'opening_snapshot: level {level} remake run {run_key} missing')
            tag = path.stem.split('_', 1)[1]
            pairs, only_o, only_r = pair_units(original['units'], run['units'])
            pairs, moved = resolve_swaps(pairs)
            for unit in only_o:
                pairing_rows.append([level, tag, unit['name'] or f'slot{unit["slot"]}', unit['slot'], 'original_only'])
            for unit in only_r:
                pairing_rows.append([level, tag, unit['id'], unit['extra']['registry_slot'], 'remake_only'])
            for o_unit, r_unit in pairs:
                units_paired += mode == 'g0'
                seen_cells[r_unit['id']].add(tuple(o_unit['cell']))
                remake_cells[r_unit['id']] = list(r_unit.get('coord', []))
                got = decode(bytes.fromhex(o_unit['record']), groups)
                got['cell'] = o_unit['cell']
                want = remake_fields(r_unit)
                slot_of = {u['id']: u['extra']['registry_slot'] for u in run['units']}
                held = o_unit['object_words']['held']
                got['held_target'] = held
                want['held_target'] = slot_of.get(r_unit.get('ai_target_id') or '', -1) + 1
                for name in unmapped:
                    unmapped_values[name][got[name]] += mode == 'g0'
                for at in UNKNOWN_OFFSETS:
                    key = f'unknown_{at:#05x}'
                    unknown_values[key][got[key]] += mode == 'g0'
                if id(o_unit) in moved:
                    rows.append([level, tag, r_unit['id'], o_unit['slot'], 'registry_slot', o_unit['slot'], r_unit['extra']['registry_slot']])
                compared['registry_slot'] += 1
                for name, value in want.items():
                    if mode == 'g0' and name in G0_SKIP:
                        continue
                    if value is None:
                        not_exported[name] += 1
                        continue
                    compared[name] += 1
                    mine = got[name]
                    if name == 'items':
                        ok = mine in feasible_bags(r_unit)
                        shown = feasible_bags(r_unit) if not ok else value
                        if not ok and r_unit['id'] in instance_items and mine in feasible_bags(with_instance_items(r_unit, instance_items[r_unit['id']])):
                            rows.append([level, tag, r_unit['id'], o_unit['slot'], 'items:evef', mine, value])
                            continue
                    elif mode == 'g1' and name in RANDOM_G1 and name in spans[r_unit['id']]:
                        low, high = spans[r_unit['id']][name]
                        ok = low <= mine <= high
                        shown = value if low == high else [low, high]
                    else:
                        ok = same(name, mine, value)
                        shown = value
                    if not ok:
                        label = cell_cause(mine, r_unit) if name == 'cell' else name
                        rows.append([level, tag, r_unit['id'], o_unit['slot'], label, mine, shown])
        # A cell the original itself varies over its runs (a random pick: equal-distance coins of the
        # walk's landing, a random-position insert) is random: compatible when the remake's cell is one
        # of the original's; otherwise labelled cell:random.
        for unit_id, cells in seen_cells.items():
            if len(cells) < 2:
                continue
            mine = [r for r in rows if r[0] == level and r[2] == unit_id and r[4].startswith('cell')]
            for r in mine:
                rows.remove(r)
            if tuple(remake_cells[unit_id]) not in cells:
                rows += [r[:4] + ['cell:random'] + r[5:] for r in mine]
    return assemble(levels, compared_levels, skipped, rows, pairing_rows, compared, not_exported, unknown_values, unmapped_values,
                    units_paired, sorted(g1_seeds_original), sorted(g1_seeds_remake))


def _values(counter: Counter, limit: int = 6) -> dict:
    nonzero = {value: n for value, n in counter.items() if n and value != 0}
    shown = sorted(nonzero.items(), key=lambda item: (-item[1], str(item[0])))[:limit]
    return {'units_nonzero': sum(nonzero.values()), 'distinct': len(nonzero), 'top': [[_hex(v), n] for v, n in shown]}


def _hex(value) -> object:
    return f'{value:#x}' if isinstance(value, int) and value > 0xffff else value


def leaderboard(rows: list[list], pairing_rows: list[list]) -> list[dict]:
    units: dict[str, set] = defaultdict(set)
    levels: dict[str, set] = defaultdict(set)
    count = Counter()
    modes: dict[str, set] = defaultdict(set)
    presence = [[level, tag, unit, slot, f'presence:{kind}'] for level, tag, unit, slot, kind in pairing_rows]
    for level, tag, unit, _slot, name, *_ in rows + presence:
        units[name].add((level, unit))
        levels[name].add(level)
        count[name] += 1
        modes[name].add(tag.split('_')[0])
    board = []
    for name in sorted(count, key=lambda n: (-len(units[n]), -count[n], n)):
        note = FIELD_NOTES.get(name, {})
        board.append({'field': name, 'diff_units': len(units[name]), 'diff_rows': count[name], 'modes': sorted(modes[name]),
                      'levels': sorted(levels[name]), 'reading': note.get('reading', ''), 'remake': note.get('remake', ''),
                      'attribution': note.get('attribution', '')})
    return board


def assemble(levels, compared_levels, skipped, rows, pairing_rows, compared, not_exported, unknown_values, unmapped_values,
             units_paired, seeds_original, seeds_remake) -> dict:
    rows.sort(key=lambda r: (r[0], r[1], r[3], r[4]))
    pairing_rows.sort(key=lambda r: (r[0], r[1], r[3], r[2]))
    board = leaderboard(rows, pairing_rows)
    per_level = []
    for level in compared_levels:
        mine = [r for r in rows if r[0] == level]
        per_level.append({'level': level, 'diff_rows': len(mine), 'fields': dict(sorted(Counter(r[4] for r in mine).items())),
                          'pairing': sum(1 for r in pairing_rows if r[0] == level)})
    compared_fields = sorted(compared)
    self_check = {name: sum(1 for r in rows if r[4] == name) for name in SELF_CHECK}
    return {
        'schema': SCHEMA, 'evidence_tier': 'runtime-measured',
        'tools': ['tools/hsltools/probes/_opening_snapshot.py', 'tests/diagnostics/export_opening_snapshot.gd',
                  'tools/hsltools/probes/opening_snapshot.py'],
        'moment': 'original: first 0x407340 entry after 0x42da60 (opening scripts and births done, round 1 unsorted); '
                  'remake: create → InitialRosterGrowthRules → begin_battle',
        'modes': {'g0': 'growth false both sides, deterministic but for the carry bag', 'g1': 'real births; RANDOM_G1 fields by remake range',
                  'g1_seeds_original': seeds_original, 'g1_seeds_remake': [seeds_remake[0], seeds_remake[-1]] if seeds_remake else []},
        'totals': {'battles': len(levels), 'compared': len(compared_levels), 'units': units_paired, 'fields': len(compared_fields),
                   'diff_rows': len(rows), 'diff_units': len({(r[0], r[2]) for r in rows}), 'pairing_rows': len(pairing_rows),
                   'unknown_offsets': len(UNKNOWN_OFFSETS), 'unmapped_named': len(unmapped_values)},
        'self_check': self_check,
        'skipped': skipped,
        'leaderboard': board,
        'compared_fields': {name: compared[name] for name in compared_fields},
        'not_exported': dict(sorted(not_exported.items())),
        'unmapped_named': {name: _values(counter) for name, counter in sorted(unmapped_values.items())},
        'unknown_offsets': {name: _values(counter) for name, counter in sorted(unknown_values.items())},
        'levels': per_level,
        'pairing_rows': pairing_rows,
        'rows_columns': ['level', 'run', 'unit', 'slot', 'field', 'original', 'remake'],
        'rows': rows,
    }


def render_json(report: dict) -> str:
    """One key per line at the top; lists of rows one row per line."""
    parts = []
    for key, value in report.items():
        if isinstance(value, list) and value and isinstance(value[0], (list, dict)):
            body = '[\n' + ',\n'.join('  ' + json.dumps(item, ensure_ascii=False) for item in value) + '\n ]'
        elif isinstance(value, dict) and len(json.dumps(value, ensure_ascii=False)) > 200:
            body = '{\n' + ',\n'.join(f'  {json.dumps(k, ensure_ascii=False)}: {json.dumps(v, ensure_ascii=False)}' for k, v in value.items()) + '\n }'
        else:
            body = json.dumps(value, ensure_ascii=False)
        parts.append(f' {json.dumps(key)}: {body}')
    return '{\n' + ',\n'.join(parts) + '\n}\n'


def render_md(report: dict) -> str:
    t = report['totals']
    lines = ['# 开局盘面全字段对拍（opening_snapshot）', '',
             f'_由 `python3 tools/hsl.py generate opening_snapshot` 从 `{REPORT_JSON}` 生成，勿手改。_', '',
             f'- 战斗 {t["battles"]}，对拍 {t["compared"]}；配对单位 {t["units"]}；比较字段 {t["fields"]}；'
             f'差异 {t["diff_rows"]} 行／{t["diff_units"]} 个单位；配对缺位 {t["pairing_rows"]} 行',
             f'- 自检（已修三类，应为 0）：' + '，'.join(f'{k} {v}' for k, v in report['self_check'].items()),
             f'- 未映射：命名字段 {t["unmapped_named"]} 个、unknown 偏移 {t["unknown_offsets"]} 个（只报告不比较）', '',
             '## 排行榜', '', '| 字段 | 差异单位 | 行 | 模式 | 关卡 | 原版读法 | 重制现状 | 归因 |', '|---|---:|---:|---|---|---|---|---|']
    for row in report['leaderboard']:
        levels = '、'.join(map(str, row['levels'][:12])) + ('…' if len(row['levels']) > 12 else '')
        lines.append(f'| {row["field"]} | {row["diff_units"]} | {row["diff_rows"]} | {"/".join(row["modes"])} | {levels} | '
                     f'{row["reading"]} | {row["remake"]} | {row["attribution"]} |')
    lines += ['', '## 按关卡', '', '| 关 | 差异行 | 配对缺位 | 字段 |', '|---:|---:|---:|---|']
    for row in report['levels']:
        if row['diff_rows'] or row['pairing']:
            fields = '，'.join(f'{k} {v}' for k, v in row['fields'].items())
            lines.append(f'| {row["level"]} | {row["diff_rows"]} | {row["pairing"]} | {fields} |')
    if report['skipped']:
        lines += ['', '## 未对拍', ''] + [f'- {s["level"]}：{s["reason"]}' for s in report['skipped']]
    return '\n'.join(lines) + '\n'


def summary(report: dict) -> str:
    t = report['totals']
    check = ','.join(f'{k}:{v}' for k, v in report['self_check'].items())
    return (f'OPENING_SNAPSHOT_CHECK_PASS battles={t["battles"]} compared={t["compared"]} units={t["units"]} fields={t["fields"]} '
            f'diff_rows={t["diff_rows"]} diff_units={t["diff_units"]} unknown_offsets={t["unknown_offsets"]} self_check={check}')


def validate(report: dict, md: str) -> None:
    if report.get('schema') != SCHEMA:
        raise ValueError(f'schema {report.get("schema")!r} is not {SCHEMA}')
    rows = report['rows']
    if report['totals']['diff_rows'] != len(rows) or report['totals']['diff_units'] != len({(r[0], r[2]) for r in rows}):
        raise ValueError('totals do not recount from the rows')
    recount = leaderboard([list(r) for r in rows], [list(r) for r in report['pairing_rows']])
    if [(b['field'], b['diff_units'], b['diff_rows']) for b in recount] != [(b['field'], b['diff_units'], b['diff_rows']) for b in report['leaderboard']]:
        raise ValueError('leaderboard does not recount from the rows')
    missing = [b['field'] for b in report['leaderboard'] if not (b['reading'] and b['attribution'])]
    if missing:
        raise ValueError(f'differing fields without a reading／attribution note (FIELD_NOTES): {missing}')
    broken = {name: n for name, n in report['self_check'].items() if n}
    if broken:
        raise ValueError(f'self-check fields differ (max_hp／stamina／items were fixed): {broken}')
    if md != render_md(report):
        raise ValueError(f'{REPORT_MD} is not the rendering of {REPORT_JSON}')


class OpeningSnapshotTask(Task):
    name = 'opening_snapshot'
    family = 'development'  # a diff report over content/generated/hsl/development, not an evidence-packet probe
    outputs = (REPORT_JSON, REPORT_MD)
    scripts = ('tools/hsltools/probes/opening_snapshot.py', 'tools/hsltools/probes/_opening_snapshot.py')
    replaces = ()

    def check(self, ctx: Context) -> str:
        try:
            report = json.loads((ctx.root / REPORT_JSON).read_text(encoding='utf-8'))
            validate(report, (ctx.root / REPORT_MD).read_text(encoding='utf-8'))
        except (OSError, ValueError, KeyError) as error:
            raise CheckFailed(f'{self.name}: {error}') from error
        return summary(report)

    def generate(self, ctx: Context) -> str:
        report = build(ctx.root / 'ignored/opening_snapshot')
        md = render_md(report)
        validate(report, md)
        (ctx.root / REPORT_JSON).write_text(render_json(report), encoding='utf-8')
        (ctx.root / REPORT_MD).write_text(md, encoding='utf-8')
        return summary(report)


def tasks() -> list[Task]:
    return [OpeningSnapshotTask()]


def main(argv: list[str] | None = None) -> int:
    """Development view without the note／self-check gate: the leaderboard and sample rows."""
    import argparse
    parser = argparse.ArgumentParser(description='Opening snapshot diff from ignored/opening_snapshot (no write).')
    parser.add_argument('--rows', type=int, default=5, help='sample rows per field')
    parser.add_argument('--field', action='append', default=[], help='print every row of this field')
    parser.add_argument('--levels', help='comma list (default: every autoplay level)')
    args = parser.parse_args(argv)
    report = build(RAW, [int(x) for x in args.levels.split(',')] if args.levels else None)
    print(json.dumps(report['totals'], ensure_ascii=False))
    print('self_check', report['self_check'], 'skipped', report['skipped'])
    for row in report['leaderboard']:
        print(f'{row["field"]:<18} units={row["diff_units"]:<5} rows={row["diff_rows"]:<5} modes={"/".join(row["modes"])} levels={row["levels"][:20]}')
        sample = [r for r in report['rows'] if r[4] == row['field']]
        for r in (sample if row['field'] in args.field else sample[:args.rows]):
            print('    ', json.dumps(r, ensure_ascii=False))
    print('pairing', len(report['pairing_rows']), report['pairing_rows'][:20])
    print('not_exported', report['not_exported'])
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
