#!/usr/bin/env python3
"""Decompile one hsl01.exe function address into ignored/static/hsl01/decompiled/.

Raw decompiled C stays ignored. Tracked summaries must come from a separate
compact packet — this wrapper only makes reverse engineering repeatable.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # hsltools
from hsltools.paths import ORIGINAL_EXE

DEFAULT_EXE = ORIGINAL_EXE
DEFAULT_OUT = Path("ignored/static/hsl01/decompiled")
DEFAULT_PROJECT = "hsl01_core"


def _normalize_addr(raw: str) -> str:
    text = raw.strip().lower()
    if text.startswith("0x"):
        value = int(text, 16)
    else:
        value = int(text, 0)
    return f"0x{value:x}"


def decompile(
    exe: Path,
    addr: str,
    out_dir: Path,
    project: str,
    backend: str,
) -> Path:
    addr = _normalize_addr(addr)
    out_dir.mkdir(parents=True, exist_ok=True)
    suffix = "pdg.c" if backend == "pdg" else "pdd.c"
    out_path = out_dir / f"{addr}.{suffix}"
    cmd = [
        "r2",
        "-e",
        "bin.cache=true",
        "-e",
        "scr.color=0",
        "-qc",
        f"Po {project}; s {addr}; af; {backend}",
        str(exe),
    ]
    completed = subprocess.run(cmd, check=False, capture_output=True, text=True)
    body = completed.stdout
    if completed.returncode != 0 or "You need to install the plugin" in body or not body.strip():
        raise RuntimeError(
            f"r2 {backend} failed for {addr}: {completed.stderr.strip() or completed.returncode}"
        )
    header = (
        f"/* generated by tools/hsl_exe_decompile.py */\n"
        f"/* exe={exe} addr={addr} backend={backend} project={project} */\n"
    )
    out_path.write_text(header + body, encoding="utf-8")
    meta = {
        "schema": "hsl_exe_decompile_meta.v1",
        "addr": addr,
        "backend": backend,
        "project": project,
        "exe": str(exe),
        "output": str(out_path),
        "bytes": out_path.stat().st_size,
    }
    meta_path = out_dir / f"{addr}.{suffix}.meta.json"
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("addr", help="Function address, e.g. 0x409a60")
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--project", default=DEFAULT_PROJECT)
    parser.add_argument(
        "--backend",
        choices=("pdg", "pdd"),
        default="pdg",
        help="pdg=r2ghidra (preferred C), pdd=r2dec",
    )
    args = parser.parse_args()
    if not args.exe.is_file():
        print(f"missing exe: {args.exe}", file=sys.stderr)
        return 2
    path = decompile(args.exe, args.addr, args.out_dir, args.project, args.backend)
    print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
